apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: two-tier-app-binding
subjects:
  - kind: ServiceAccount
    name: two-tier-app-sa
    namespace: default
roleRef:
  kind: Role
  name: two-tier-app-role
  apiGroup: rbac.authorization.k8s.io