apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: app-alerts
  namespace: monitoring
  labels:
    release: kube-prometheus-stack
spec:
  groups:
    - name: app.rules
      rules:
        - alert: HighCPUUsage
          expr: sum(rate(container_cpu_usage_seconds_total[1m])) > 0.5
          for: 2m
          labels:
            severity: warning
          annotations:
            summary: "High CPU usage detected"

        - alert: PodCrashLoop
          expr: kube_pod_container_status_restarts_total > 3
          for: 2m
          labels:
            severity: critical
          annotations:
            summary: "Pod restarting frequently"

        - alert: PodDown
          expr: kube_deployment_status_replicas_available{deployment="two-tier-app", namespace="default"} < 1
          for: 1m
          labels:
            severity: critical
          annotations:
            summary: "Application has 0 running pods"